# Dependencies
plugins: [jekyll-paginate]

# Features
excerpt_separator: <!--more-->
categories: "quant|finance|maths|physics|crypto|programming|machine-learning"


# Permalinks
permalink:        /:year/:month/:day/:title/

# Setup
title:            Analytic Musings
tagline:          'Always learning. Always improving'
description:      'Always learning. Always improving'
url:               'https://analytic-musings.com'
baseurl:          
imageurl:       '/assets/images/'

author:
  name:           'Ryan Chew'
  email:        'ryan1997chew@gmail.com'


# Custom vars
future: TRUE
version:          2.1.0

github:
  repo:           https://github.com/ryanczm/quant

social:
    linkedin: https://www.linkedin.com/in/ryan-chew-49272a19a/
    twitter: https://twitter.com/ryan_czm

# Structure
paginate:         10

collections:
  notes:
      output: true
      permalink: /notes/:path/

# Conversion
markdown:    kramdown
highlighter: rouge

# Markdown Processors
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge