# Dependencies
plugins: 
  - jekyll-paginate
  - jekyll-seo-tag


# Features
excerpt_separator: <!--more-->
categories: "quant|finance|maths|commodities"


# Permalinks
permalink:        /:year/:month/:day/:title/

# Setup
title:            Analytic Musings
tagline:          '-'
description:      '-'
url:               'https://analytic-musings.com'
baseurl:          
imageurl:       '/assets/images/'

author:
  name:           'Ryan Chew'
  email:        'ryan1997chew@gmail.com'


# Custom vars
future: TRUE
version:          2.1.0

github:
  repo:           https://www.youtube.com/watch?v=dQw4w9WgXcQ&list=RDdQw4w9WgXcQ&start_radio=1

social:
    linkedin: https://www.youtube.com/watch?v=dQw4w9WgXcQ&list=RDdQw4w9WgXcQ&start_radio=1
    twitter: https://twitter.com/ryan_czm

# Structure
paginate:         10

collections:
  notes:
      output: true
      permalink: /notes/:path/

# Conversion
markdown:    kramdown
highlighter: rouge

# Markdown Processors
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge